package com.itree.entity;
// Generated 2015-11-15 16:02:00 by Hibernate Tools 4.0.0

/**
 * TFiletype generated by hbm2java
 */
public class TFiletype implements java.io.Serializable {

	private Integer id;
	private TFile TFile;
	private String type;

	public TFiletype() {
	}

	public TFiletype(TFile TFile) {
		this.TFile = TFile;
	}

	public TFiletype(TFile TFile, String type) {
		this.TFile = TFile;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TFile getTFile() {
		return this.TFile;
	}

	public void setTFile(TFile TFile) {
		this.TFile = TFile;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
