package com.itree.entity;
// Generated 2015-11-15 16:02:00 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class TUser implements java.io.Serializable {

	private Integer id;
	private TDuty TDuty;
	private TFile TFile;
	private String userName;
	private int userSex;
	private String userHoby;
	private String userMotto;
	private String userTel;
	private String userProfile;
	private int userStatus;
	private Set<TFile> TFiles = new HashSet<TFile>(0);
	private Set<TNews> TNewses = new HashSet<TNews>(0);
	private Set<TLogin> TLogins = new HashSet<TLogin>(0);

	public TUser() {
	}

	public TUser(TDuty TDuty, String userName, int userSex, int userStatus) {
		this.TDuty = TDuty;
		this.userName = userName;
		this.userSex = userSex;
		this.userStatus = userStatus;
	}

	public TUser(TDuty TDuty, TFile TFile, String userName, int userSex, String userHoby, String userMotto,
			String userTel, String userProfile, int userStatus, Set<TFile> TFiles, Set<TNews> TNewses,
			Set<TLogin> TLogins) {
		this.TDuty = TDuty;
		this.TFile = TFile;
		this.userName = userName;
		this.userSex = userSex;
		this.userHoby = userHoby;
		this.userMotto = userMotto;
		this.userTel = userTel;
		this.userProfile = userProfile;
		this.userStatus = userStatus;
		this.TFiles = TFiles;
		this.TNewses = TNewses;
		this.TLogins = TLogins;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TDuty getTDuty() {
		return this.TDuty;
	}

	public void setTDuty(TDuty TDuty) {
		this.TDuty = TDuty;
	}

	public TFile getTFile() {
		return this.TFile;
	}

	public void setTFile(TFile TFile) {
		this.TFile = TFile;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public int getUserSex() {
		return this.userSex;
	}

	public void setUserSex(int userSex) {
		this.userSex = userSex;
	}

	public String getUserHoby() {
		return this.userHoby;
	}

	public void setUserHoby(String userHoby) {
		this.userHoby = userHoby;
	}

	public String getUserMotto() {
		return this.userMotto;
	}

	public void setUserMotto(String userMotto) {
		this.userMotto = userMotto;
	}

	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	public String getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(String userProfile) {
		this.userProfile = userProfile;
	}

	public int getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(int userStatus) {
		this.userStatus = userStatus;
	}

	public Set<TFile> getTFiles() {
		return this.TFiles;
	}

	public void setTFiles(Set<TFile> TFiles) {
		this.TFiles = TFiles;
	}

	public Set<TNews> getTNewses() {
		return this.TNewses;
	}

	public void setTNewses(Set<TNews> TNewses) {
		this.TNewses = TNewses;
	}

	public Set<TLogin> getTLogins() {
		return this.TLogins;
	}

	public void setTLogins(Set<TLogin> TLogins) {
		this.TLogins = TLogins;
	}

}
