package com.itree.entity;
// Generated 2015-11-15 16:02:00 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TFile generated by hbm2java
 */
public class TFile implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TUser TUser;
	private String fileProfile;
	private String fileTitle;
	private String filePath;
	private Integer filtetypeId;
	private Integer fileStatus;
	private Date uploadTime;
	private Set<TFiletype> TFiletypes = new HashSet<TFiletype>();
	private Set<TNews> TNewses = new HashSet<TNews>();
	private Set<TUser> TUsers = new HashSet<TUser>();

	public TFile() {
	}

	public TFile(String fileTitle) {
		this.fileTitle = fileTitle;
	}

	public TFile(TUser TUser, String fileProfile, String fileTitle, String filePath, Integer filtetypeId,
			Integer fileStatus, Date uploadTime, Set<TFiletype> TFiletypes, Set<TNews> TNewses, Set<TUser> TUsers) {
		this.TUser = TUser;
		this.fileProfile = fileProfile;
		this.fileTitle = fileTitle;
		this.filePath = filePath;
		this.filtetypeId = filtetypeId;
		this.fileStatus = fileStatus;
		this.uploadTime = uploadTime;
		this.TFiletypes = TFiletypes;
		this.TNewses = TNewses;
		this.TUsers = TUsers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getFileProfile() {
		return this.fileProfile;
	}

	public void setFileProfile(String fileProfile) {
		this.fileProfile = fileProfile;
	}

	public String getFileTitle() {
		return this.fileTitle;
	}

	public void setFileTitle(String fileTitle) {
		this.fileTitle = fileTitle;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Integer getFiltetypeId() {
		return this.filtetypeId;
	}

	public void setFiltetypeId(Integer filtetypeId) {
		this.filtetypeId = filtetypeId;
	}

	public Integer getFileStatus() {
		return this.fileStatus;
	}

	public void setFileStatus(Integer fileStatus) {
		this.fileStatus = fileStatus;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public Set<TFiletype> getTFiletypes() {
		return this.TFiletypes;
	}

	public void setTFiletypes(Set<TFiletype> TFiletypes) {
		this.TFiletypes = TFiletypes;
	}

	public Set<TNews> getTNewses() {
		return this.TNewses;
	}

	public void setTNewses(Set<TNews> TNewses) {
		this.TNewses = TNewses;
	}

	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

}
