package com.itree.entity;
// Generated 2015-11-15 16:02:00 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TMessage generated by hbm2java
 */
public class TMessage implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String messageContent;
	private Date messageDate;
	private String messageTel;
	private int messageStatus;

	public TMessage() {
	}

	public TMessage(int messageStatus) {
		this.messageStatus = messageStatus;
	}

	public TMessage(String messageContent, Date messageDate, String messageTel, int messageStatus) {
		this.messageContent = messageContent;
		this.messageDate = messageDate;
		this.messageTel = messageTel;
		this.messageStatus = messageStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMessageContent() {
		return this.messageContent;
	}

	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	public Date getMessageDate() {
		return this.messageDate;
	}

	public void setMessageDate(Date messageDate) {
		this.messageDate = messageDate;
	}

	public String getMessageTel() {
		return this.messageTel;
	}

	public void setMessageTel(String messageTel) {
		this.messageTel = messageTel;
	}

	public int getMessageStatus() {
		return this.messageStatus;
	}

	public void setMessageStatus(int messageStatus) {
		this.messageStatus = messageStatus;
	}

}
